services:
  php-app:
    build:
      context: .
      dockerfile: dockerFile
    ports: 
      - "2200:2200"
    volumes:
      - .:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
      - DB_HOST=mysql
      - DB_USER=admin
      - DB_PASSWORD=a2pP3QASzx5p1ZPQWLsm1
      - DB_NAME=asino777
    depends_on:
      - mysql
    links:
      - mysql
    networks:
      - shared-network

  mysql:
    image: mysql:8.0
    build:
      context: .
      dockerfile: dockerFile-mysql
    environment:
      MYSQL_ROOT_PASSWORD: a2pP3QASzx5p1ZPQWLsm1
      MYSQL_DATABASE: asino777
      MYSQL_USER: admin
      MYSQL_PASSWORD: a2pP3QASzx5p1ZPQWLsm1
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - target: 2201
        published: 2201
        protocol: tcp
        mode: host
    networks:
      - shared-network

volumes:
  mysql-data:

networks:
  shared-network:
    external: true
