<?php
require(dirname(__DIR__, 1) . "/system/config.php");
if (session_status() !== PHP_SESSION_ACTIVE) {
  session_start();
}

if (!isset($_SESSION['hash']) || empty($_SESSION['hash'])) {
  header('Location: /');
  die();
}

require(dirname(__DIR__, 1) . "/panels/header.php");
require(dirname(__DIR__, 1) . "/panels/sidebar.php");
require_once(dirname(__DIR__, 1) . "/panels/footer.php");

?>

<div class="main-container scrollable-1 ScrollY" id="main-content">
  <div class="favorite-container">
    <div class="favorite-inner">
      <div class="mybets-stack-container">
        <div class="mybets-wrap">
          <div class="mybets-header-stack">
            <div class="mybets-title-group">
              <h1 class="mybets-heading">
                <svg data-ds-icon="Security" width="24" height="24" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" fill="none" class="inline-block shrink-0 text-[var(--color-grey-200)]"><!---->
                  <path fill="currentColor" fill-rule="evenodd" d="M11.18 3a2.12 2.12 0 0 1 1.64 0l7.08 2.57c.73.31 1.2 1 1.2 1.77v1.65c0 8.62-4.98 11.2-7.57 12.61-.95.52-2.11.52-3.06 0C7.88 20.18 2.9 17.61 2.9 8.99V7.34c0-.76.47-1.46 1.2-1.77zM12 7a2.5 2.5 0 0 0-2.5 2.5c0 1.03.62 1.9 1.5 2.29V15c0 .55.45 1 1 1s1-.45 1-1v-3.21c.88-.39 1.5-1.27 1.5-2.29A2.5 2.5 0 0 0 12 7" clip-rule="evenodd"></path>
                </svg>
                <? echo htmlspecialchars($translations['policies']) ?>
              </h1>
            </div>
            <a class="mybets-close-button" href="/casino/home">
              <svg class="mybets-close-icon" width="20" height="20" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" fill="none">
                <path fill="currentColor" d="M4.293 4.293a1 1 0 0 1 1.338-.069l.076.069L12 10.586l6.293-6.293.076-.069a1 1 0 0 1 1.407 1.407l-.069.076L13.414 12l6.293 6.293.069.076a1 1 0 0 1-1.407 1.406l-.076-.068L12 13.414l-6.293 6.293a1 1 0 0 1-1.414-1.414L10.586 12 4.293 5.707l-.068-.076a1 1 0 0 1 .068-1.338"></path>
              </svg>
            </a>
          </div>
        </div>
        <div class="mybets-content-stack">
          <div class="mybets-sidebar-card" style="">
            <div class="mybets-nav-outer-wrapper">
              <div class="mybets-nav-wrapper">
                <button class="mybets-nav-link mybets-nav-active" data-testid="global-navbar-Term-tab" onclick="window.location.href='/policies/terms'">
                  <span class="mybets-nav-text">Terms of Service</span>
                </button>
                <button class="mybets-nav-link mybets-nav-active" data-testid="global-navbar-AML-tab">
                  <span class="mybets-nav-text"> Anti-Money Laundering</span>
                </button>
                <button class="mybets-nav-link" data-testid="global-navbar-Privacy-tab" onclick="window.location.href='/policies/privacy'">
                  <span class="mybets-nav-text"> Privacy</span>
                </button>


                <div class="mybets-nav-dash"></div>
              </div>
            </div>
          </div>

          <div class="card variant-default p-6 overflow-hidden relative page-card svelte-1vf4wu3" id='terms'>
            <div style="">
              <div class="layout-spacing variant-normal svelte-tm71ti no-bottom-spacing"><!----><!---->
                <div class="wrap svelte-1y88mpk "><!----><!----><!----><!----><!----><!----> <!---->
                  <div class="content-block svelte-k165h5"><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[--><!---->
                    <h1 type="heading" tag="h1" size="xl" variant="neutral-default" class="text-neutral-default ds-heading-xl" data-ds-text="true"><!--[--><!--[--><span id="Anti-Money_Laundering,_Anti-Terrorist_Financing_statement">Anti-Money Laundering, Anti-Terrorist Financing statement</span><!--]--><!--]--><!----><!----></h1><!----><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[--><!----><!---->
                    <h2 type="heading" tag="h2" size="lg" variant="neutral-default" class="text-neutral-default ds-heading-lg" data-ds-text="true"><!----><!----><!----><span id="1._Company_Business_Model">1. Company Business Model</span></h2><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!---->
                    <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->Medium Rare N.V. (“</span><!----><!----><!----><span type="body" size="md" tag="span" strong="true" class="ds-body-md-strong" data-ds-text="true"><!---->Stake</span><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->” or the “</span><!----><!----><!----><span type="body" size="md" tag="span" strong="true" class="ds-body-md-strong" data-ds-text="true"><!---->Company</span><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->”) is a company incorporated under Curaçao Law that was established in 2017 and operates the online casino </span><!----><!----><a class="[font-family:var(--ds-font-family-default)] [font-variant-numeric:var(--ds-font-variant-numeric,lining-nums_tabular-nums)] [font-feature-settings:var(--ds-font-feature-settings,&quot;salt&quot;_on)] relative justify-center rounded-(--ds-radius-md) [font-weight:var(--ds-font-weight-thick)] ring-offset-background transition disabled:pointer-events-none disabled:opacity-50 focus-visible:outline-2 focus-visible:outline-offset-2 active:scale-[0.98] [text-decoration-line:underline] [text-decoration-style:solid] [text-decoration-skip-ink:none] [text-decoration-thickness:8%] [text-underline-offset:25%] hover:[text-decoration-thickness:14%] bg-transparent text-grey-200 hover:bg-transparent hover:text-white focus-visible:outline-hidden var(--ds-font-size-sm) !bg-transparent !text-white [&amp;_svg]:!text-white focus-visible:text-white focus-visible!:[&amp;_svg]:text-white inline-flex items-center gap-1 whitespace-normal" href="/" data-sveltekit-reload="off" data-sveltekit-preload-data="off" data-sveltekit-noscroll="off" external="false"><!----><span type="body" tag="span" size="md" class="ds-body-md" data-ds-text="true"><!---->www.stake.com</span><!----></a><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->. Stake is licensed by the Curaçao Gaming Authority under license number OGL/2024/1451/0918. Stake presently supports users in more than 169 countries globally.</span></p><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[--><!---->
                    <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!--[--><!--[!--><!--[!--><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true">As part of its global operations, Stake has established compliance measures commensurate with its services and products that are reasonably designed to deter and detect illicit activity on its platform. Such measures include onboarding and compliance screenings of its customers and transaction action-based controls.<!----><!----></span><!----><!--]--><!--]--><!--]--><!----><!----></p><!----><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[--><!----><!---->
                    <h2 type="heading" tag="h2" size="lg" variant="neutral-default" class="text-neutral-default ds-heading-lg" data-ds-text="true"><!----><!----><!----><span id="2._Company_Policy_Statement">2. Company Policy Statement</span></h2><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!---->
                    <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->Stake is not a financial institution within the meaning of applicable law of Curaçao and is accordingly not directly subject to the statutes and regulations applicable to certain financial institutions, money transfer, or virtual asset service providers. However, in accordance with the 2016 Regulations for Anti-Money Laundering and Combating the Financing of Terrorism (“</span><!----><!----><!----><span type="body" size="md" tag="span" strong="true" class="ds-body-md-strong" data-ds-text="true"><!---->AML/CFT</span><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->”) applicable for the Curaçao jurisdiction as provided by the Curaçao Gaming Control Board, Stake expressly prohibits and rejects the use of Stake products for any form of illicit activity, including money laundering, terrorist financing or trade sanctions violations, consistent with various national anti-money laundering (“</span><!----><!----><!----><span type="body" size="md" tag="span" strong="true" class="ds-body-md-strong" data-ds-text="true"><!---->AML</span><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->”) laws, regulations and norms. Stake continues to monitor norm setting parameters promulgated by the Financial Action Task Force (“</span><!----><!----><!----><span type="body" size="md" tag="span" strong="true" class="ds-body-md-strong" data-ds-text="true"><!---->FATF</span><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->”) and certain gaming trade groups in addition to the Curaçao Gaming Control Board and will take necessary action as it deems appropriate to reflect changes in law.</span></p><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!----><!----><!----><!----><!----><!----><!----><!----><!---->
                    <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->Stake’s intention is to follow global best practices in guarding against Stake products being used to facilitate such activities. Those best practices include:</span></p><!--]--><!--[!-->
                    <ul class="svelte-42q2bt">
                      <li class="level-1 svelte-42q2bt"><!---->
                        <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->Adoption of a written policy, and procedures and controls, reasonably designed to guard against money laundering, terrorist financing and trade sanctions violations;</span></p><!---->
                      </li>
                      <li class="level-1 svelte-42q2bt"><!---->
                        <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->Where appropriate, designation of a compliance officer to oversee the implementation of the policy, procedures and controls;</span></p><!---->
                      </li>
                      <li class="level-1 svelte-42q2bt"><!---->
                        <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->Provision of related education and training to relevant personnel; and</span></p><!---->
                      </li>
                      <li class="level-1 svelte-42q2bt"><!---->
                        <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->Independent reviews, monitoring and maintenance of the policy, procedures and controls.</span></p><!---->
                      </li>
                    </ul><!--]--><!--[!--><!----><!----><!----><!----><!----><!----><!----><!----><!----><!---->
                    <h3 type="heading" tag="h3" size="md" variant="neutral-default" class="text-neutral-default ds-heading-md" data-ds-text="true"><!----><!----><!----><span id="3._Definitions">3. Definitions</span></h3><!--]--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!---->
                    <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->The following defined terms are widely used in the industry:</span></p><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[--><!---->
                    <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!--[--><!--[!--><!--[!--><!----><span type="body" size="md" tag="span" strong="true" class="ds-body-md-strong" data-ds-text="true">Money Laundering:<!----><!----></span><!----><!--]--><!--]--><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!----> The process of making illegally-gained proceeds appear legal. This process is generally broken down into three steps: placement, layering and integration.</span><!--]--><!----><!----></p><!----><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!----><!----><!----><!----><!----><!----><!----><!----><!---->
                    <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><!----><span type="body" size="md" tag="span" strong="true" class="ds-body-md-strong" data-ds-text="true"><!---->Placement:</span><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!----> The process of placing unlawful proceeds into traditional financial institutions, through deposits or other avenues.</span></p><!--]--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[--><!---->
                    <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!--[--><!--[!--><!--[!--><!----><span type="body" size="md" tag="span" strong="true" class="ds-body-md-strong" data-ds-text="true">Layering:<!----><!----></span><!----><!--]--><!--]--><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->&nbsp;The process of separating proceeds of criminal activity from their origin through the use of layers of complex financial transactions, such as converting cash into traveler’s checks, money orders, wire transfers, letters of credit, stocks, bonds or purchasing assets.</span><!--]--><!----><!----></p><!----><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[--><!---->
                    <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!--[--><!--[!--><!--[!--><!----><span type="body" size="md" tag="span" strong="true" class="ds-body-md-strong" data-ds-text="true">Integration:<!----><!----></span><!----><!--]--><!--]--><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->&nbsp;Using apparently legitimate transactions to disguise the illicit proceeds, allowing the laundered funds to be distributed back to the criminal; integrating the now clean money back into normal use.</span><!--]--><!----><!----></p><!----><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[--><!---->
                    <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><!----><span type="body" size="md" tag="span" strong="true" class="ds-body-md-strong" data-ds-text="true"><!---->Suspicious Activity:</span><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!----> Activity conducted by a user or non-user using the institution where there are indications that the persons engaging in the transaction may be doing so for fraudulent or illegal purposes.</span></p><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[--><!---->
                    <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!--[--><!--[!--><!--[!--><!----><span type="body" size="md" tag="span" strong="true" class="ds-body-md-strong" data-ds-text="true">Sanctions: <!----><!----></span><!----><!--]--><!--]--><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->Sanctions are activities conducted by the international community to prohibit or constrain activities of the target of the sanctions.For example, they are used:</span><!--]--><!----><!----></p><!----><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!-->
                    <ul class="svelte-42q2bt">
                      <li class="level-1 svelte-42q2bt"><!---->
                        <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->To encourage a change in behaviour for a target country or regime;</span></p><!---->
                      </li>
                      <li class="level-1 svelte-42q2bt"><!---->
                        <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->To apply pressure on a target country to comply with set objectives;</span></p><!---->
                      </li>
                      <li class="level-1 svelte-42q2bt"><!---->
                        <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->As an enforcement tool when international peace and security has been threatened and diplomatic efforts have failed; or</span></p><!---->
                      </li>
                      <li class="level-1 svelte-42q2bt"><!---->
                        <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->To prevent and suppress the financing of terrorists or terrorist acts.</span></p><!---->
                      </li>
                    </ul><!--]--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[--><!---->
                    <h3 type="heading" tag="h2" size="lg" variant="neutral-default" class="text-neutral-default ds-heading-lg" data-ds-text="true"><!--[--><!--[--><span id="4._Governance_and_Oversight">4. Governance and Oversight</span><!--]--><!--]--><!----><!----></h3><!----><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[--><!---->
                    <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!--[--><!--[!--><!--[!--><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true">Stake has appointed a Chief Compliance Officer (“<!----><!----></span><!----><!--]--><!--]--><!----><!----><!----><span type="body" size="md" tag="span" strong="true" class="ds-body-md-strong" data-ds-text="true"><!---->CCO</span><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->”) that is responsible for coordinating the implementation of the AML Policy and policy program. The Chief Compliance Officer’s duties also include developing AML initiatives, work with other stakeholders to revising the AML policy, assessing new regulatory requirements and investigate potentially suspicious or unusual activity. Stake also provides AML training to all of its employees on a regular basis.</span><!--]--><!----><!----></p><!----><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[--><!----><!---->
                    <h2 type="heading" tag="h2" size="lg" variant="neutral-default" class="text-neutral-default ds-heading-lg" data-ds-text="true"><!----><!----><!----><span id="5._Know_Your_Customer_and_Transaction_Monitoring">5. Know Your Customer and Transaction Monitoring</span></h2><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!----><!----><!----><!----><!----><!----><!----><!----><!---->
                    <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->Stake will apply appropriate user due diligence and ongoing monitoring measures required by law. Stake will endeavour to prevent users from engaging in illicit or otherwise unauthorised activity. Stake uses a combination of its software development and other service agreements, which are enforced through internal operational features to ensure that it complies with the applicable law.</span></p><!--]--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[--><!----><!---->
                    <h3 type="heading" tag="h3" size="md" variant="neutral-default" class="text-neutral-default ds-heading-md" data-ds-text="true"><!----><!----><!----><span id="5._1._Know_Your_Customer">5. 1. Know Your Customer</span></h3><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[--><!---->
                    <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!--[--><!--[!--><!--[!--><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true">A. Customer Due Diligence<!----><!----></span><!----><!--]--><!--]--><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->.</span><!--]--><!----><!----></p><!----><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[--><!---->
                    <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->Stake has adopted a risk based CDD to enable Stake to understand the nature and purpose of the user relationship to the Stake platform in order to develop a customer risk profile. In order to do so, Stake collects certain documentary and non-documentary information at account-opening commensurate with the nature of the type account and services that Stake offers. Stake maintains different CDD for different accounts and services.</span></p><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[--><!---->
                    <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!--[--><!--[!--><!--[!--><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true">For instance, the CDD requires users go through Stake’s customer identification program (“<!----><!----></span><!----><!--]--><!--]--><!----><!----><!----><span type="body" size="md" tag="span" strong="true" class="ds-body-md-strong" data-ds-text="true"><!---->CIP</span><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->”). The CIP consists of procedures for:</span><!--]--><!----><!----></p><!----><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!-->
                    <ul class="svelte-42q2bt">
                      <li class="level-1 svelte-42q2bt"><!---->
                        <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->Collecting baseline (e.g., wallet address, email address) information</span><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!----> at account creation</span><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!----> through Stake’s user onboarding portal;</span></p><!---->
                      </li>
                      <li class="level-1 svelte-42q2bt"><!---->
                        <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->Monitoring the risk profile associated with the underlying cryptocurrency wallet used to fund the user’s account;</span></p><!---->
                      </li>
                      <li class="level-1 svelte-42q2bt"><!---->
                        <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->Maintaining records of the information used to identify the user; and</span></p><!---->
                      </li>
                      <li class="level-1 svelte-42q2bt"><!---->
                        <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->Determining if a user appears on any list of known or suspected terrorists or terrorist organisations provided to the financial institutions based on the above information.</span></p><!---->
                      </li>
                    </ul><!--]--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[--><!---->
                    <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!--[--><!--[!--><!--[!--><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true">The above steps are operationalised using the following measures:<!----><!----></span><!----><!--]--><!--]--><!--]--><!----><!----></p><!----><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!-->
                    <ul class="svelte-42q2bt">
                      <li class="level-1 svelte-42q2bt"><!---->
                        <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><em><!----><span type="body" size="md" tag="span" strong="true" class="ds-body-md-strong" data-ds-text="true"><!---->Identity and Age Verification</span><!----></em><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->. A third-party service provider will support’s Stake’s ability to determine the legitimacy of the identification information other KYC materials or information provided and will confirm that the user is permissible. The service provider also will confirm that the user does not appear to be located in a comprehensively-sanctioned or otherwise prohibited jurisdiction and will search global sanctions lists to confirm that the user does not appear thereon using onboarding information such as wallet addresses.</span></p><!---->
                      </li>
                      <li class="level-1 svelte-42q2bt"><!---->
                        <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><em><!----><span type="body" size="md" tag="span" strong="true" class="ds-body-md-strong" data-ds-text="true"><!---->Customer Information</span><!----></em><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->. Stake will collect details on each user to form a reasonable belief that Stake knows the identity of its users commensurate with the user’s risk profile. For instance, Stake may collect such details as the wallet address, name, address, country, date of birth, or postal code (collectively, “</span><!----><!----><!----><span type="body" size="md" tag="span" strong="true" class="ds-body-md-strong" data-ds-text="true"><!---->KYC Information</span><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->”). Stake will collect any of the above KYC Information prior to issuing a Stake funding address (e.g., QR code) to users. Stake does not presently allow users who are non-natural persons.Stake may, at its own description rely on the performance by another institution of some or all of the elements of our CIP.</span></p><!---->
                      </li>
                      <li class="level-1 svelte-42q2bt"><!---->
                        <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><em><!----><span type="body" size="md" tag="span" strong="true" class="ds-body-md-strong" data-ds-text="true"><!---->Geo-blocking for Prohibited Jurisdictions</span><!----></em><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->. Stake will require contractual client certifications that, through IP address-based geo-blocking, no gaming services will be offered in countries where such activity is not permitted.</span></p><!---->
                      </li>
                      <li class="level-1 svelte-42q2bt"><!---->
                        <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><em><!----><span type="body" size="md" tag="span" strong="true" class="ds-body-md-strong" data-ds-text="true"><!---->Geo-blocking for Sanctioned Jurisdictions</span><!----></em><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->. Stake also will require contractual client certifications that such users are not subject to United States, European Union, or other global sanctions or watch lists, including individuals or entities associated with the United States’ comprehensively sanctioned jurisdictions, Iran, Cuba, North Korea, Syria and the Crimean region of Ukraine. Stake will rely on various risk-based measures to verify these representations including as in the below-described know-your-user (“</span><!----><!----><!----><span type="body" size="md" tag="span" strong="true" class="ds-body-md-strong" data-ds-text="true"><!---->KYC</span><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->”) measures and through IP address-based geo-blocking.</span></p><!---->
                      </li>
                      <li class="level-1 svelte-42q2bt"><!---->
                        <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><em><!----><span type="body" size="md" tag="span" strong="true" class="ds-body-md-strong" data-ds-text="true"><!---->Contractual Prohibitions on Users Onboarding from Prohibited Jurisdictions</span><!----></em><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->. Users are notified at onboarding that Stake does not offer services in restricted jurisdictions. Stake’s policy on restricting user activity stems from a combination of its risk, fraud prevention, and AML standards, as well as any assessments associated with the permissibility of its services in certain jurisdictions.</span></p><!---->
                      </li>
                    </ul><!--]--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[--><!---->
                    <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!--[--><!--[!--><!--[!--><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true">B. Enhanced Due Diligence and Ongoing Monitoring<!----><!----></span><!----><!--]--><!--]--><!--]--><!----><!----></p><!----><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[--><!---->
                    <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->Stake performs ongoing monitoring on its users in order to detect any behaviours or indicators that might raise suspicions in regard to money laundering and terrorism financing practices. For that purpose, Stake has implemented a set of red flag indicators that help it determine such behaviours and require further action from Stake in assessing the customer information.</span></p><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[--><!---->
                    <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!--[--><!--[!--><!--[!--><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true">Whenever one of those red flags is triggered, the user account will be suspended and Stake will pursue enhanced due diligence. Enhanced KYC diligence under this policy is deemed to include, but not limit to, the provision of:<!----><!----></span><!----><!--]--><!--]--><!--]--><!----><!----></p><!----><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!-->
                    <ul class="svelte-42q2bt">
                      <li class="level-1 svelte-42q2bt"><!---->
                        <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->Full legal name;</span></p><!---->
                      </li>
                      <li class="level-1 svelte-42q2bt"><!---->
                        <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->Country of citizenship;</span></p><!---->
                      </li>
                      <li class="level-1 svelte-42q2bt"><!---->
                        <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->Permanent Address (which, for an individual, must be a residential or business street address, and for an entity, must be a principal place of business, local office or other physical location);</span></p><!---->
                      </li>
                      <li class="level-1 svelte-42q2bt"><!---->
                        <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->Identification number (either a taxpayer identification number, or, if unavailable, a passport number and country of issuance, alien identification card number or number and country of issuance of another government-issued document evidencing nationality or residence and bearing a photograph or similar safeguard);</span></p><!---->
                      </li>
                      <li class="level-1 svelte-42q2bt"><!---->
                        <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->Identification Document; and</span></p><!---->
                      </li>
                      <li class="level-1 svelte-42q2bt"><!---->
                        <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->Source of Funds and Source of Wealth.</span></p><!---->
                      </li>
                    </ul><!--]--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[--><!---->
                    <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!--[--><!--[!--><!--[!--><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true">Stake may use third party service provider to verify any of the above information as determined to establish a reasonable basis to know the true identity of the user where the user’s activity warrants such action.<!----><!----></span><!----><!--]--><!--]--><!--]--><!----><!----></p><!----><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[--><!---->
                    <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->C. Acceptance Policy</span></p><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[--><!---->
                    <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!--[--><!--[!--><!--[!--><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true">Stake will not accept a and will block the users that:<!----><!----></span><!----><!--]--><!--]--><!--]--><!----><!----></p><!----><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!-->
                    <ul class="svelte-42q2bt">
                      <li class="level-1 svelte-42q2bt"><!---->
                        <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->Do not provide the identification information requested by Stake;</span></p><!---->
                      </li>
                      <li class="level-1 svelte-42q2bt"><!---->
                        <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->Provide fake identification documents;</span></p><!---->
                      </li>
                      <li class="level-1 svelte-42q2bt"><!---->
                        <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->Try to use different means to deceive about their location;</span></p><!---->
                      </li>
                      <li class="level-1 svelte-42q2bt"><!---->
                        <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->Are from restricted or prohibited jurisdictions; or</span></p><!---->
                      </li>
                      <li class="level-1 svelte-42q2bt"><!---->
                        <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->Are subjected to United States, European Union, or other global sanctions or watch lists;</span></p><!---->
                      </li>
                      <li class="level-1 svelte-42q2bt"><!---->
                        <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->Are gambling addicted or have mental health issues;</span></p><!---->
                      </li>
                      <li class="level-1 svelte-42q2bt"><!---->
                        <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->Its source of funds are originated or exchanges in restricted jurisdictions;</span></p><!---->
                      </li>
                    </ul><!--]--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[--><!---->
                    <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!--[--><!--[!--><!--[!--><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true">Stake reserves the right to block and suspend player for any other reasons at its own description<!----><!----></span><!----><!--]--><!--]--><!--]--><!----><!----></p><!----><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[--><!----><!---->
                    <h2 type="heading" tag="h3" size="md" variant="neutral-default" class="text-neutral-default ds-heading-md" data-ds-text="true"><!----><!----><!----><span id="5.2._Transactions_Monitoring">5.2. Transactions Monitoring</span></h2><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[--><!---->
                    <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!--[--><!--[!--><!--[!--><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true">Stake is firmly committed to complying with economic and trade sanctions programs imposed by jurisdictions in which the firm conducts business. For that purpose Stake established a transaction monitoring program with controls and processes to identify and detect any unusual activity in real time and in its ongoing monitoring.<!----><!----></span><!----><!--]--><!--]--><!--]--><!----><!----></p><!----><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!----><!----><!----><!----><!----><!----><!----><!----><!---->
                    <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->Stake will conduct ongoing monitoring on a regular basis using rule-based systems developed in-house and others from third-party vendors to review user history and patterns of activity to detect and report any unusual activity as required and to develop and implement any additional controls or limits in its platform.</span></p><!--]--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[--><!---->
                    <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->Stake implemented procedures addressing the following two key components of unusual or suspicious activity management:</span></p><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!-->
                    <ul class="svelte-42q2bt">
                      <li class="level-1 svelte-42q2bt"><!---->
                        <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->identification of unusual activity through methods of identification may include employee and customer identification, law enforcement inquiries, other referrals, or transaction and surveillance monitoring system reports; and</span></p><!---->
                      </li>
                      <li class="level-1 svelte-42q2bt"><!---->
                        <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->alert management that focuses on processes used to investigate, evaluate and document identified unusual or potentially suspicious activity.</span></p><!---->
                      </li>
                    </ul><!--]--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[!--><!--[--><!---->
                    <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->Stake will use the following processes to achieve both goals:</span></p><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!-->
                    <ul class="svelte-42q2bt">
                      <li class="level-1 svelte-42q2bt"><!---->
                        <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><em><!----><span type="body" size="md" tag="span" strong="true" class="ds-body-md-strong" data-ds-text="true"><!---->Transaction Monitoring for Sanctioned or Prohibited Jurisdictions</span><!----></em><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->. Stake may in its reasonable discretion impose certain due diligence requests at user balance withdrawal. Stake presently conducts a mixture of manual and automated transaction monitoring processes to identify “red flag” behaviour. Where such red flag behaviour is identified, Stake may refuse to process any withdrawal attempts or collect additional information from the recipient. Stake will further endeavour to limit any attempted user account funding from prohibited jurisdictions (which are identified in the Stake user facing disclosures and updated from time to time internally) where the associated wallet address indicates that the user or the user’s funds are located in such a prohibited jurisdiction. For instance, Stake may prohibit a user from funding their Stake account using a known U.S. based exchange wallet as such assets indicate that the user is a U.S. person. Users will have the ability to rebut any suspension with additional information as part of Stake’s ongoing transaction monitoring and user due diligence standards.</span></p><!---->
                      </li>
                      <li class="level-1 svelte-42q2bt"><!---->
                        <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><em><!----><span type="body" size="md" tag="span" strong="true" class="ds-body-md-strong" data-ds-text="true"><!---->Screening for Sanctioned Parties</span><!----></em><!----><!----><em><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->. </span><!----></em><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->Prior to issuing a Stake funding address to a user, Stake will screen a user’s wallet address against applicable sanctions databases. Such screening measures will rely on third party blockchain forensics vendors such as Chainalysis. Stake will periodically re-screen wallet addresses against such databases.</span></p><!---->
                      </li>
                      <li class="level-1 svelte-42q2bt"><!---->
                        <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><em><!----><span type="body" size="md" tag="span" strong="true" class="ds-body-md-strong" data-ds-text="true"><!---->Identification of Unusual Activity</span><!----></em><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->. Stake will monitor account activity for unusual size, volume, pattern or type of transactions, taking into account risk factors and red flags that are appropriate to its business. Monitoring will be conducted running regular reports of unusual, high risk, or suspicious user activity.</span></p><!---->
                      </li>
                      <li class="level-1 svelte-42q2bt"><!---->
                        <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><em><!----><span type="body" size="md" tag="span" strong="true" class="ds-body-md-strong" data-ds-text="true"><!---->Anti-Mixing Measures.</span><!----></em><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->Stake will utilise software designed to detect other suspicious deposit or withdrawal patterns. Such instances will be dealt with on a case-by-case basis, depending on the perceived level of risk. In such instances, a user may be required to explain their methodology and purpose for using the platform.</span></p><!---->
                      </li>
                      <li class="level-1 svelte-42q2bt"><!---->
                        <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><em><!----><span type="body" size="md" tag="span" strong="true" class="ds-body-md-strong" data-ds-text="true"><!---->Chainalysis Review.</span><!----></em><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!----> Every single crypto deposit or withdrawal both indirect and direct will run through Chainalysis and reviewed for signs of fraud or suspicious behaviour. A user’s account will be suspended and reviewed upon alert of potential illicit behaviour. Sufficient proof of wealth may be requested from high-risk accounts. Stake may refuse to withdraw to certain “high-risk” addresses as determined in consultation with Chainalysis risk scoring.</span></p><!---->
                      </li>
                      <li class="level-1 svelte-42q2bt"><!---->
                        <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><em><!----><span type="body" size="md" tag="span" strong="true" class="ds-body-md-strong" data-ds-text="true"><!---->Withdrawal Threshold KYC.</span><!----></em><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!----> Additionally, and independently, every account, wherever or with whomever associated, will be suspended until adequate KYC diligence occurs once that account reaches a withdrawal threshold dependent on the accounts risk characterisation over the life of the account.</span></p><!---->
                      </li>
                    </ul><!--]--><!----><!----><!----><!----><!----><!----><!----><!----><!----><!---->
                    <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->D. Other Ongoing Monitoring Controls</span></p><!----><!----><!----><!----><!----><!----><!----><!----><!----><!---->
                    <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->Additionally to the above mentioned controlling procedures, Stake has also implemented the following procedures to complement its know your customer and ongoing monitoring procedures:</span></p><!---->
                    <ul class="svelte-42q2bt">
                      <li class="level-1 svelte-42q2bt"><!---->
                        <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><em><!----><span type="body" size="md" tag="span" strong="true" class="ds-body-md-strong" data-ds-text="true"><!---->Ban Evasion Detection</span><!----></em><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->. In addition, Stake will utilise third-party service provider software designed to detect the use by one user of multiple accounts. This software relies on detection of links between the same devices used to access multiple accounts. Such instances will be dealt with on a case-by-case basis, depending on the perceived level of risk. In such instances, a user may be required to explain their methodology and purpose for using the platform. Stake accounts are funded by users using local (non-custodial) or hosted (custodial) wallets. In addition to a Chainalysis screening, Stake monitors user activity within the Stake platform and any withdrawals must meet Stake’s and its third-party service provider’s verification processes. Stake further prohibits peer-to-peer account transfers within the Stake platform infrastructure. Any attempts to circumvent this restriction will be treated as a red flag.</span></p><!---->
                      </li>
                      <li class="level-1 svelte-42q2bt"><!---->
                        <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><em><!----><span type="body" size="md" tag="span" strong="true" class="ds-body-md-strong" data-ds-text="true"><!---->Time Zone Monitoring.</span><!----></em><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!----> Stake has implemented time zone controls that detects the users device information and crosses it with restricted jurisdiction to understand if they are trying to use geo location software to hide the jurisdictions where they are connecting from.</span></p><!---->
                      </li>
                      <li class="level-1 svelte-42q2bt"><!---->
                        <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><em><!----><span type="body" size="md" tag="span" strong="true" class="ds-body-md-strong" data-ds-text="true"><!---->Products and Services Review. </span><!----></em><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->Stake will establish additional procedures to avoid facilitating user attempts to exploit the Stake platform. Stake has a robust set of user-facing terms that users attest to in order to utilise the Stake platform. Stake will establish certain additional safeguards to mitigate against the risk of such misuse. For instance, Stake may establish policies or procedures for limiting which user assets can be onboarded to the Stake platform. Stake lists the assets that are available for use on the Stake platform. Stake does not allow the use of anonymity enhancing technologies such as mixers, tumblers, or certain coins and tokens. Where Stake becomes aware that an anonymity enhancing technology is being used on the Stake platform, Stake will disallow such use.</span></p><!---->
                      </li>
                      <li class="level-1 svelte-42q2bt"><!---->
                        <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><em><!----><span type="body" size="md" tag="span" strong="true" class="ds-body-md-strong" data-ds-text="true"><!---->Vendor Management. </span><!----></em><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->Stake works with reputable third-party service providers as part of its compliance infrastructure. Stake will periodically assess the strength of its key third party service providers to determine if additional services are needed, the third-party service provider is not performing consistent with its contractual obligations, or if other remedial action is necessary for Stake to comply with this policy. Stake may request information from any third-party service provider as part of its vendor review process.</span></p><!---->
                      </li>
                      <li class="level-1 svelte-42q2bt"><!---->
                        <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><em><!----><span type="body" size="md" tag="span" strong="true" class="ds-body-md-strong" data-ds-text="true"><!---->Compliance Innovation</span><!----></em></p><!---->
                      </li>
                    </ul><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!---->
                    <h2 type="heading" tag="h2" size="lg" variant="neutral-default" class="text-neutral-default ds-heading-lg" data-ds-text="true"><!----><!----><!----><span id="6._Education_and_Training">6. Education and Training</span></h2><!----><!----><!----><!----><!----><!----><!----><!----><!----><!---->
                    <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->Stake, with the assistance of its legal counsel and under the oversight of its CCO, may provide employees AML, anti-terrorist financing and trade sanctions compliance training on a periodic basis, as deemed appropriate.</span></p><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!---->
                    <h2 type="heading" tag="h2" size="lg" variant="neutral-default" class="text-neutral-default ds-heading-lg" data-ds-text="true"><!----><!----><!----><span id="7._Reporting">7. Reporting</span></h2><!----><!----><!----><!----><!----><!----><!----><!----><!----><!---->
                    <p type="body" tag="p" size="md" class="ds-body-md inline-text" data-ds-text="true"><!----><!----><!----><!----><!----><span type="body" size="md" tag="span" strong="false" class="ds-body-md" data-ds-text="true"><!---->Stake is obliged to report any unusual or suspicious transactions, in accordance with the National Ordinance. Customers that are identified as being on a sanctions list, linked to money laundering or terrorism financing or other criminal activities will be reported as suspicious activity to the regulator.</span></p><!--]-->
                  </div>
                </div><!---->
              </div><!---->
            </div> <!----><!---->
          </div>
        </div>
      </div>

    </div>
  </div><? render_footer($translations) ?>
</div>